-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-08 23:45:14 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE kandydaci (
    identyfikator          NUMBER(5) NOT NULL,
    imie                   VARCHAR2(20) NOT NULL,
    nazwisko               VARCHAR2(20) NOT NULL,
    data_aplikacji         DATE NOT NULL,
    doswiadczenie_zawodowe NUMBER(3, 1) NOT NULL,
    obecne_stanowisko      VARCHAR2(50),
    wyksztalcenie          VARCHAR2(20) NOT NULL,
    nr_telefonu            NUMBER(9) NOT NULL,
    e_mail                 VARCHAR2(30),
    cv                     CHAR(1) NOT NULL,
    portfolio              CHAR(1) NOT NULL
);

ALTER TABLE kandydaci ADD CONSTRAINT kandydaci_pk PRIMARY KEY ( identyfikator );

CREATE TABLE rekrutacja (
    identyfikator               NUMBER(5) NOT NULL,
    kandydaci_identyfikator     NUMBER(5) NOT NULL,
    rekruterzy_identyfikator    NUMBER(5) NOT NULL,
    stanowiska_nazwa_stanowiska VARCHAR2(50),
    etap_rekrutacji             NUMBER(1) NOT NULL,
    data_rekrutacji             DATE,
    ocena                       NUMBER(3, 1)
);

ALTER TABLE rekrutacja ADD CONSTRAINT rekrutacja_pk PRIMARY KEY ( identyfikator );

CREATE TABLE rekruterzy (
    identyfikator NUMBER(5) NOT NULL,
    imie          VARCHAR2(20) NOT NULL,
    nazwisko      VARCHAR2(20) NOT NULL,
    e_mail        VARCHAR2(30) NOT NULL
);

ALTER TABLE rekruterzy ADD CONSTRAINT rekruterzy_pk PRIMARY KEY ( identyfikator );

CREATE TABLE stanowiska (
    identyfikator    NUMBER(5) NOT NULL,
    nazwa_stanowiska VARCHAR2(50) NOT NULL
);

ALTER TABLE stanowiska ADD CONSTRAINT stanowiska_pk PRIMARY KEY ( nazwa_stanowiska );

CREATE TABLE umiejetnosci_na_stanowisko (
    wym_umiejetnosci_umiejetnosc VARCHAR2(100) NOT NULL,
    stanowiska_nazwa_stanowiska  VARCHAR2(50) NOT NULL
);

ALTER TABLE umiejetnosci_na_stanowisko ADD CONSTRAINT rel PRIMARY KEY ( wym_umiejetnosci_umiejetnosc,
                                                                        stanowiska_nazwa_stanowiska );

CREATE TABLE wymagane_umiejetnosci (
    identyfikator NUMBER(5) NOT NULL,
    umiejetnosc   VARCHAR2(100) NOT NULL
);

ALTER TABLE wymagane_umiejetnosci ADD CONSTRAINT wymagane_umiejetnosci_pk PRIMARY KEY ( umiejetnosc );

ALTER TABLE rekrutacja
    ADD CONSTRAINT rekrutacja_kandydaci_fk FOREIGN KEY ( kandydaci_identyfikator )
        REFERENCES kandydaci ( identyfikator );

ALTER TABLE rekrutacja
    ADD CONSTRAINT rekrutacja_rekruterzy_fk FOREIGN KEY ( rekruterzy_identyfikator )
        REFERENCES rekruterzy ( identyfikator );

ALTER TABLE rekrutacja
    ADD CONSTRAINT rekrutacja_stanowiska_fk FOREIGN KEY ( stanowiska_nazwa_stanowiska )
        REFERENCES stanowiska ( nazwa_stanowiska );

ALTER TABLE umiejetnosci_na_stanowisko
    ADD CONSTRAINT rel_stanowiska_fk FOREIGN KEY ( stanowiska_nazwa_stanowiska )
        REFERENCES stanowiska ( nazwa_stanowiska );

ALTER TABLE umiejetnosci_na_stanowisko
    ADD CONSTRAINT rel_wymagane_umiejetnosci_fk FOREIGN KEY ( wym_umiejetnosci_umiejetnosc )
        REFERENCES wymagane_umiejetnosci ( umiejetnosc );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
